// Color palettes for tasks and queues
export const COLOR_PALETTES = {
  vibrant: [
    { name: 'Red', value: '#ef4444' },
    { name: 'Orange', value: '#f97316' },
    { name: 'Amber', value: '#f59e0b' },
    { name: 'Yellow', value: '#eab308' },
    { name: 'Lime', value: '#84cc16' },
    { name: 'Green', value: '#22c55e' },
    { name: 'Emerald', value: '#10b981' },
    { name: 'Teal', value: '#14b8a6' },
    { name: 'Cyan', value: '#06b6d4' },
    { name: 'Sky', value: '#0ea5e9' },
    { name: 'Blue', value: '#3b82f6' },
    { name: 'Indigo', value: '#6366f1' },
    { name: 'Violet', value: '#8b5cf6' },
    { name: 'Purple', value: '#a855f7' },
    { name: 'Fuchsia', value: '#d946ef' },
    { name: 'Pink', value: '#ec4899' },
    { name: 'Rose', value: '#f43f5e' },
  ],
  pastel: [
    { name: 'Pastel Red', value: '#fca5a5' },
    { name: 'Pastel Orange', value: '#fdba74' },
    { name: 'Pastel Amber', value: '#fcd34d' },
    { name: 'Pastel Yellow', value: '#fde047' },
    { name: 'Pastel Lime', value: '#bef264' },
    { name: 'Pastel Green', value: '#86efac' },
    { name: 'Pastel Emerald', value: '#6ee7b7' },
    { name: 'Pastel Teal', value: '#5eead4' },
    { name: 'Pastel Cyan', value: '#67e8f9' },
    { name: 'Pastel Sky', value: '#7dd3fc' },
    { name: 'Pastel Blue', value: '#93c5fd' },
    { name: 'Pastel Indigo', value: '#a5b4fc' },
    { name: 'Pastel Violet', value: '#c4b5fd' },
    { name: 'Pastel Purple', value: '#d8b4fe' },
    { name: 'Pastel Fuchsia', value: '#f0abfc' },
    { name: 'Pastel Pink', value: '#f9a8d4' },
  ],
  muted: [
    { name: 'Muted Red', value: '#dc2626' },
    { name: 'Muted Orange', value: '#ea580c' },
    { name: 'Muted Amber', value: '#d97706' },
    { name: 'Muted Yellow', value: '#ca8a04' },
    { name: 'Muted Lime', value: '#65a30d' },
    { name: 'Muted Green', value: '#16a34a' },
    { name: 'Muted Emerald', value: '#059669' },
    { name: 'Muted Teal', value: '#0d9488' },
    { name: 'Muted Cyan', value: '#0891b2' },
    { name: 'Muted Sky', value: '#0284c7' },
    { name: 'Muted Blue', value: '#2563eb' },
    { name: 'Muted Indigo', value: '#4f46e5' },
    { name: 'Muted Violet', value: '#7c3aed' },
    { name: 'Muted Purple', value: '#9333ea' },
    { name: 'Muted Fuchsia', value: '#c026d3' },
    { name: 'Muted Pink', value: '#db2777' },
  ],
  neutral: [
    { name: 'Gray', value: '#6b7280' },
    { name: 'Slate', value: '#64748b' },
    { name: 'Zinc', value: '#71717a' },
    { name: 'Stone', value: '#78716c' },
  ],
};

export const DEFAULT_TASK_COLORS = COLOR_PALETTES.vibrant;
export const DEFAULT_QUEUE_COLORS = [
  '#91aedc', '#71b47b', '#efe195', '#ea8080', 
  '#b09cde', '#e88bb9', '#76e2f6', '#b4d582'
];
